name: discover-weekly-archive-run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Runs every Monday at 6am UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Python environment
        run: |
          python3.10 -m venv env
          source env/bin/activate
          
      - name: Install dependencies
        run: |    
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Discover Weekly Archive
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          USER_ID: ${{ secrets.USER_ID }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python discover_weekly.py
